// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsj0ZaFCmMKljuuADSdZjXDAVBQD9k6YE',
    appId: '1:325867424702:web:3ef411dd6994f8dd0e47ef',
    messagingSenderId: '325867424702',
    projectId: 'brain-tumor-36503',
    authDomain: 'brain-tumor-36503.firebaseapp.com',
    storageBucket: 'brain-tumor-36503.firebasestorage.app',
    measurementId: 'G-7YTV42FWEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3fE3ikY8BcEPWmMIXZTR8l6ApoeFrs6k',
    appId: '1:325867424702:android:08cd6b2fec5a41560e47ef',
    messagingSenderId: '325867424702',
    projectId: 'brain-tumor-36503',
    storageBucket: 'brain-tumor-36503.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0tyePor77r8p2k8KX401wdKpTy8fE6tg',
    appId: '1:325867424702:ios:06af2746d2fe4b390e47ef',
    messagingSenderId: '325867424702',
    projectId: 'brain-tumor-36503',
    storageBucket: 'brain-tumor-36503.firebasestorage.app',
    iosBundleId: 'com.example.brainTumor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0tyePor77r8p2k8KX401wdKpTy8fE6tg',
    appId: '1:325867424702:ios:06af2746d2fe4b390e47ef',
    messagingSenderId: '325867424702',
    projectId: 'brain-tumor-36503',
    storageBucket: 'brain-tumor-36503.firebasestorage.app',
    iosBundleId: 'com.example.brainTumor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsj0ZaFCmMKljuuADSdZjXDAVBQD9k6YE',
    appId: '1:325867424702:web:2cd09ba07de5c2190e47ef',
    messagingSenderId: '325867424702',
    projectId: 'brain-tumor-36503',
    authDomain: 'brain-tumor-36503.firebaseapp.com',
    storageBucket: 'brain-tumor-36503.firebasestorage.app',
    measurementId: 'G-D74X1RXL7E',
  );
}
